name: Notify n8n on GitHub Pages Build

on:
  page_build:
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to n8n
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"status\": \"deployed\", \"repo\": \"${{ github.repository }}\", \"branch\": \"${{ github.ref_name }}\", \"path\": \"docs\", \"commit\": \"${{ github.sha }}\"}" \
            "https://n8n.srv1034010.hstgr.cloud/webhook/fcd6e2a2-d660-48b6-ac80-42f755d66c39"
